=== dice-group/LIMES/limes-core/resources/limes.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT LIMES (PREFIX*, SOURCE, TARGET, (METRIC | MLALGORITHM), ACCEPTANCE, REVIEW, EXECUTION*, GRANULARITY*, OUTPUT*)>
<!ELEMENT PREFIX (NAMESPACE, LABEL)>
<!ELEMENT NAMESPACE (#PCDATA)>
<!ELEMENT LABEL (#PCDATA)>
<!ELEMENT SOURCE (ID, ENDPOINT, GRAPH*, VAR, PAGESIZE, RESTRICTION+, PROPERTY+, TYPE*)>
<!ELEMENT TARGET (ID, ENDPOINT, GRAPH*, VAR, PAGESIZE, RESTRICTION+, PROPERTY+, TYPE*)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT RESTRICTION (#PCDATA)>
<!ELEMENT METRIC (#PCDATA)>
<!ELEMENT ACCEPTANCE (THRESHOLD, FILE, RELATION)>
<!ELEMENT REVIEW (THRESHOLD, FILE, RELATION)>
<!ELEMENT RELATION (#PCDATA)>
<!ELEMENT ENDPOINT (#PCDATA)>
<!ELEMENT GRAPH (#PCDATA)>
<!ELEMENT VAR (#PCDATA)>
<!ELEMENT CLASS (#PCDATA)>
<!ELEMENT PROPERTY (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)>
<!ELEMENT THRESHOLD (#PCDATA)>
<!ELEMENT FILE (#PCDATA)>
<!ELEMENT PAGESIZE (#PCDATA)>
<!ELEMENT GRANULARITY (#PCDATA)>
<!ELEMENT OUTPUT (#PCDATA)>
<!ELEMENT EXECUTION (REWRITER*, PLANNER*, ENGINE*)*>
<!ELEMENT REWRITER (#PCDATA)>
<!ELEMENT PLANNER (#PCDATA)>
<!ELEMENT ENGINE (#PCDATA)>
<!ELEMENT MLALGORITHM  (NAME*, TYPE*, TRAINING*, PARAMETER*)*>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT TRAINING (#PCDATA)>
<!ELEMENT PARAMETER  (NAME*, VALUE*)*>
<!ELEMENT VALUE (#PCDATA)>

=== dice-group/LIMES/limes-core/src/main/resources/datasets/persons1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
		<LABEL>rdf</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
		<LABEL>rdfs</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.okkam.org/ontology_person1.owl#</NAMESPACE>
		<LABEL>okkamperson1</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.okkam.org/ontology_person2.owl#</NAMESPACE>
		<LABEL>okkamperson2</LABEL>
	</PREFIX>
<SOURCE>
		<ID>person11</ID>
		<ENDPOINT>src/main/resources/datasets/Persons1/person11.nt</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?x rdf:type okkamperson1:Person</RESTRICTION>
		<PROPERTY>okkamperson1:surname AS lowercase</PROPERTY>
		<PROPERTY>okkamperson1:given_name AS lowercase</PROPERTY>
		<PROPERTY>okkamperson1:age AS lowercase</PROPERTY>
		<PROPERTY>okkamperson1:phone_numer</PROPERTY>		
		<PROPERTY>okkamperson1:soc_sec_id</PROPERTY>
		<PROPERTY>okkamperson1:has_address AS cleaniri</PROPERTY>
		<PROPERTY>okkamperson1:date_of_birth AS lowercase</PROPERTY>
		<TYPE>N3</TYPE>
</SOURCE>
	
	<TARGET>
		<ID>person12</ID>
		<ENDPOINT>src/main/resources/datasets/Persons1/person12.nt</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?y rdf:type okkamperson2:Person</RESTRICTION>
		<PROPERTY>okkamperson2:surname AS lowercase</PROPERTY>
		<PROPERTY>okkamperson2:given_name AS lowercase</PROPERTY>
		<PROPERTY>okkamperson2:age AS lowercase</PROPERTY>
		<PROPERTY>okkamperson2:phone_numer</PROPERTY>
		<PROPERTY>okkamperson2:has_address AS cleaniri</PROPERTY>
		<PROPERTY>okkamperson2:soc_sec_id</PROPERTY>
		<PROPERTY>okkamperson2:date_of_birth AS lowercase</PROPERTY>
		<TYPE>N3</TYPE>
	</TARGET>	

	<METRIC>levenshtein(x.okkamperson1:surname, y.okkamperson2:surname)</METRIC>

	<ACCEPTANCE>
		<THRESHOLD>0.98</THRESHOLD>
		<FILE>accepted.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.95</THRESHOLD>
		<FILE>reviewme.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
	
		<EXECUTION>
		<REWRITER>default</REWRITER>
		<PLANNER>default</PLANNER>
		<ENGINE>default</ENGINE>
	</EXECUTION>
	<OUTPUT>N3</OUTPUT>
</LIMES>

=== dice-group/LIMES/GUI/src/test/resources/gui/testConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
		<LABEL>rdf</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
		<LABEL>rdfs</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://xmlns.com/foaf/0.1/</NAMESPACE>
		<LABEL>foaf</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/</NAMESPACE>
		<LABEL>drugbank</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www4.wiwiss.fu-berlin.de/sider/resource/sider/</NAMESPACE>
		<LABEL>sider</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://dbpedia.org/ontology/</NAMESPACE>
		<LABEL>dbpedia</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://dbpedia.org/property/</NAMESPACE>
		<LABEL>dbpedia-p</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://purl.org/dc/terms/</NAMESPACE>
		<LABEL>dc</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseasome/</NAMESPACE>
		<LABEL>diseasome</LABEL>
	</PREFIX>
	<SOURCE>
		<ID>dbpedia</ID>
		<ENDPOINT>http://dbpedia.org/sparql</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?x rdf:type dbpedia:Drug</RESTRICTION>
		<PROPERTY>rdfs:label AS nolang->lowercase</PROPERTY>
	</SOURCE>
	<TARGET>
		<ID>dbpedia</ID>
		<ENDPOINT>http://dbpedia.org/sparql</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?y rdf:type dbpedia:Drug</RESTRICTION>
		<PROPERTY>rdfs:label AS nolang->lowercase RENAME name</PROPERTY>
	</TARGET>
	<METRIC>AND(jaccard(x.rdfs:label,y.name)|0.5, trigram(x.rdfs:label,y.name)|0.7)</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.8</THRESHOLD>
		<FILE>dbpedia_dbpedia_duplicates.nt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.5</THRESHOLD>
		<FILE>dbpedia_dbpedia_reviewme.nt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
  	 <EXECUTION>
	      <REWRITER>default</REWRITER>
	      <PLANNER>default</PLANNER>
	      <ENGINE>default</ENGINE>
         </EXECUTION>
	<OUTPUT>TTL</OUTPUT>
</LIMES>

=== dice-group/LIMES/limes-core/resources/lgd-lgd-optional-properties.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://geovocab.org/geometry#</NAMESPACE>
		<LABEL>geom</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.opengis.net/ont/geosparql#</NAMESPACE>
		<LABEL>geos</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://linkedgeodata.org/ontology/</NAMESPACE>
		<LABEL>lgdo</LABEL>
	</PREFIX>
    <PREFIX>
        <NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
        <LABEL>rdfs</LABEL>
    </PREFIX>
	<SOURCE>
		<ID>linkedgeodata</ID>
		<ENDPOINT>http://linkedgeodata.org/sparql</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>2000</PAGESIZE>
		<RESTRICTION>?x a lgdo:RelayBox</RESTRICTION>
		<PROPERTY>geom:geometry/geos:asWKT RENAME polygon</PROPERTY>
		<OPTIONAL_PROPERTY>rdfs:label</OPTIONAL_PROPERTY>
	</SOURCE>
	<TARGET>
		<ID>linkedgeodata</ID>
		<ENDPOINT>http://linkedgeodata.org/sparql</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>2000</PAGESIZE>
		<RESTRICTION>?y a lgdo:RelayBox</RESTRICTION>
		<PROPERTY>geom:geometry/geos:asWKT RENAME polygon</PROPERTY>
                <OPTIONAL_PROPERTY>rdfs:label</OPTIONAL_PROPERTY>
	</TARGET>
	<METRIC>geo_hausdorff(x.polygon, y.polygon)</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.9</THRESHOLD>
		<FILE>lgd_relaybox_verynear.nt</FILE>
		<RELATION>lgdo:near</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.5</THRESHOLD>
		<FILE>lgd_relaybox_near.nt</FILE>
		<RELATION>lgdo:near</RELATION>
	</REVIEW>

	<EXECUTION>
		<REWRITER>default</REWRITER>
		<PLANNER>default</PLANNER>
		<ENGINE>default</ENGINE>
	</EXECUTION>

	<OUTPUT>TAB</OUTPUT>
</LIMES>

=== dice-group/LIMES/limes-core/src/main/resources/datasets/PublicationData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 rel. 3 sp1 (http://www.altova.com)-->
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<SOURCE>
		<ID>dblp2</ID>
		<ENDPOINT>src/main/resources/datasets/DBLP-ACM/DBLP2.csv</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>-1</PAGESIZE>
		<RESTRICTION></RESTRICTION>
		<PROPERTY>title AS lowercase</PROPERTY>
		<PROPERTY>authors AS lowercase</PROPERTY>
		<PROPERTY>venue AS lowercase</PROPERTY>
		<!--<PROPERTY>year AS number</PROPERTY> --> 
		<TYPE>CSV</TYPE>
	</SOURCE>
	<TARGET>
		<ID>acm</ID>
		<ENDPOINT>src/main/resources/datasets/DBLP-ACM/ACM.csv</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>-1</PAGESIZE>
		<RESTRICTION></RESTRICTION>
		<PROPERTY>title AS lowercase</PROPERTY>
		<PROPERTY>authors AS lowercase</PROPERTY>
		<PROPERTY>venue AS lowercase</PROPERTY>
		<!--<PROPERTY>year AS number</PROPERTY>-->
		<TYPE>CSV</TYPE>
	</TARGET>
	
	<METRIC>AND(trigrams(x.title,y.title)|0.11,euclidean(x.year,y.year)|0.83)</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.62</THRESHOLD>
		<FILE>pub_accepted.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.5</THRESHOLD>
		<FILE>pub_reviewme.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
	<EXECUTION>
		<REWRITER>default</REWRITER>
		<PLANNER>default</PLANNER>
		<ENGINE>default</ENGINE>
	</EXECUTION>
	<OUTPUT>N3</OUTPUT>
</LIMES>

=== dice-group/LIMES/limes-core/src/main/resources/datasets/restaurants.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
		<LABEL>rdf</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
		<LABEL>rdfs</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	
	<PREFIX>
		<NAMESPACE>http://www.okkam.org/ontology_restaurant2.owl#</NAMESPACE>
		<LABEL>okkamrestaurant2</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.okkam.org/ontology_restaurant1.owl#</NAMESPACE>
		<LABEL>okkamrestaurant1</LABEL>
	</PREFIX>
<SOURCE>
		<ID>restaurant1</ID>
		<ENDPOINT>src/main/resources/datasets/Restaurants/restaurant1.nt</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?x rdf:type okkamrestaurant1:Restaurant</RESTRICTION>
		<PROPERTY>okkamrestaurant1:has_address AS lowercase</PROPERTY>
		<PROPERTY>okkamrestaurant1:category AS lowercase</PROPERTY>
		<PROPERTY>okkamrestaurant1:phone_number</PROPERTY>
		<PROPERTY>okkamrestaurant1:name AS lowercase</PROPERTY>

		<TYPE>N3</TYPE>
</SOURCE>
	
	<TARGET>
		<ID>restaurant2</ID>
		<ENDPOINT>src/main/resources/datasets/Restaurants/restaurant2.nt</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?x rdf:type okkamrestaurant2:Restaurant</RESTRICTION>
		<PROPERTY>okkamrestaurant2:has_address AS lowercase</PROPERTY>
		<PROPERTY>okkamrestaurant2:phone_number</PROPERTY>
		<PROPERTY>okkamrestaurant2:name AS lowercase</PROPERTY>

		<TYPE>N3</TYPE>
	</TARGET>	

	<METRIC>levenshtein(x.okkamrestaurant1:name, y.okkamrestaurant2:name)</METRIC>

	<ACCEPTANCE>
		<THRESHOLD>0.98</THRESHOLD>
		<FILE>accepted.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.95</THRESHOLD>
		<FILE>reviewme.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
	
		<EXECUTION>
		<REWRITER>default</REWRITER>
		<PLANNER>default</PLANNER>
		<ENGINE>default</ENGINE>
	</EXECUTION>
	<OUTPUT>N3</OUTPUT>
</LIMES>

=== dice-group/LIMES/limes-core/src/test/resources/dating1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
  <PREFIX>
    <NAMESPACE>myprop#</NAMESPACE>
    <LABEL>prop</LABEL>
  </PREFIX>

  <SOURCE>
    <ID>datingcom</ID>
    <ENDPOINT>src/test/resources/dating1.nt</ENDPOINT>
    <VAR>?x</VAR>
    <PAGESIZE>1000</PAGESIZE>
    <!--<RESTRICTION>?x prop:has_pet "dog"</RESTRICTION>-->
    <RESTRICTION></RESTRICTION>
    <PROPERTY>prop:name AS lowercase</PROPERTY>
    <PROPERTY>prop:email AS lowercase</PROPERTY>
    <PROPERTY>prop:has_pet AS lowercase</PROPERTY>

    <TYPE>N3</TYPE>
  </SOURCE>

  <TARGET>
    <ID>cupidcom</ID>
    <ENDPOINT>src/test/resources/dating2.nt</ENDPOINT>
    <VAR>?y</VAR>
    <PAGESIZE>1000</PAGESIZE>
    <!--<RESTRICTION>?y prop:speaks "english"</RESTRICTION>-->
    <RESTRICTION></RESTRICTION>
    <PROPERTY>prop:name AS lowercase</PROPERTY>
    <PROPERTY>prop:email AS lowercase</PROPERTY>
    <PROPERTY>prop:speaks AS lowercase</PROPERTY>

    <TYPE>N3</TYPE>
  </TARGET>
  <METRIC>simple_edit_distance(x.prop:name, y.prop:name)</METRIC>
  <!--
  <METRIC>AND(exactmatch(x.prop:email, y.prop:email)|0.9, mongeelkan(x.prop:name, y.prop:name)|0.07)</METRIC>
  <METRIC>AND(exactmatch(x.prop:email, y.prop:email)|0.9, simple_edit_distance(x.prop:name, y.prop:name)|0.07)</METRIC>
  <METRIC>exactmatch(x.prop:email, y.prop:email)</METRIC>
  <METRIC>levenshtein(x.prop:name, y.prop:name)</METRIC>
  <METRIC>simple_edit_distance(x.prop:name, y.prop:name)</METRIC>
  -->

  <ACCEPTANCE>
    <THRESHOLD>0.5</THRESHOLD>
    <FILE>my-accepted.txt</FILE>
    <RELATION>verySimilar</RELATION>
  </ACCEPTANCE>
  <REVIEW>
    <THRESHOLD>0.01</THRESHOLD>
    <FILE>my-reviewme.txt</FILE>
    <RELATION>quiteSimilar</RELATION>
  </REVIEW>

  <OUTPUT>N3</OUTPUT>
</LIMES>
